AWSTemplateFormatVersion: 2010-09-09
Description: 
  - Template for testing/demoing Vision One Container Security

Mappings:
  RegionMap:
    ap-northeast-1:
      HostedId: "Z1YSHQZHG15GKL"
      AZs: 'ap-northeast-1a,ap-northeast-1b,ap-northeast-1c'
    ap-northeast-2:
      HostedId: "Z20JF4UZKIW1U8"
      AZs: 'ap-northeast-2a,ap-northeast-2b,ap-northeast-2c'
    ap-northeast-3:
      HostedId: "Z5LXEXXYW11ES"
      AZs: 'ap-northeast-3a,ap-northeast-3b,ap-northeast-3c'
    us-east-2:
      HostedId: "ZOJJZC49E0EPZ"
      AZs: 'us-east-2a,us-east-2b,us-east-2c'
    us-east-1:
      HostedId: "Z1UJRXOUMOOFQ8"
      AZs: 'us-east-1a,us-east-1b,us-east-1c,us-east-1d'
    us-west-1:
      HostedId: "Z2MUQ32089INYE"
      AZs: 'us-west-1a,us-west-1b'
    us-west-2:
      HostedId: "Z2OJLYMUO9EFXC"
      AZs: 'us-west-2a,us-west-2b,us-west-2c'
    ap-south-1:
      HostedId: "Z3VO1THU9YC4UR"
      AZs: 'ap-south-1a,ap-south-1b,ap-south-1c'
    ap-southeast-1:
      HostedId: "ZL327KTPIQFUL"
      AZs: 'ap-southeast-1a,ap-southeast-1b,ap-southeast-1c'
    ap-southeast-2:
      HostedId: "Z2RPCDW04V8134"
      AZs: 'ap-southeast-2a,ap-southeast-2b,ap-southeast-2c'
    ca-central-1:
      HostedId: "Z19DQILCV0OWEC"
      AZs: 'ca-central-1a,ca-central-1b,ca-central-1d'
    eu-central-1:
      HostedId: "Z1U9ULNL0V5AJ3"
      AZs: 'eu-central-1a,eu-central-1b,eu-central-1c'
    eu-west-1:
      HostedId: "ZLY8HYME6SFDD"
      AZs: 'eu-west-1a,eu-west-1b,eu-west-1c'
    eu-west-2:
      HostedId: "ZJ5UAJN8Y3Z2Q"
      AZs: 'eu-west-2a,eu-west-2b,eu-west-2c'
    eu-west-3:
      HostedId: "Z3KY65QIEKYHQQ"
      AZs: 'eu-west-3a,eu-west-3b,eu-west-3c'
    eu-north-1:
      HostedId: "Z3UWIKFBOOGXPP"
      AZs: 'eu-north-1a,eu-north-1b,eu-north-1c'
    sa-east-1:
      HostedId: "ZCMLWB8V5SYIT"
      AZs: 'sa-east-1a,sa-east-1b,sa-east-1c'
    # ap-east-1:
    #   HostedId: "Z3FD1VL90ND7K5"
    #   AZs: 'ap-east-1a,ap-east-1b,ap-east-1c'
    # me-south-1:
    #   HostedId: "Z20ZBPC0SS8806"


Parameters:
  BuildEks:
    Type: String
    AllowedValues: ["true", "false"]
    Default: "true"
  BuildEcs:
    Type: String
    AllowedValues: ["true", "false"]
    Default: "true"
Conditions:
  BuildEks:
    !Equals [ true, !Ref BuildEks ]
  BuildEcs:
    !Equals [ true, !Ref BuildEcs ]

Resources:
  VPCStack:
      Type: AWS::CloudFormation::Stack
      Properties:
        TemplateURL: !Sub 'https://v1-demo-environments.s3.amazonaws.com/utils/vpc.template.yaml'
        Parameters:
          NumberOfAZs: 3
          AvailabilityZones: !FindInMap
            - RegionMap
            - !Ref 'AWS::Region'
            - AZs
          CreateAdditionalPrivateSubnets: 'false'

  EKSStack:
    Condition: BuildEks
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        KeyPairName: !GetAtt KeyPairStack.Outputs.KeyPairName
        QSS3BucketName: v1-demo-environments
        QSS3KeyPrefix: utils/eks
        QSS3BucketRegion: !Sub ${AWS::Region}
        RemoteAccessCIDR: '0.0.0.0/0'
        AdditionalEKSAdminUserArn: ""
        AdditionalEKSAdminRoleArn: ""
        VPCID: !GetAtt VPCStack.Outputs.VPCID
        PublicSubnet1ID: !GetAtt VPCStack.Outputs.PublicSubnet1ID
        PublicSubnet2ID: !GetAtt VPCStack.Outputs.PublicSubnet2ID
        PublicSubnet3ID: !GetAtt VPCStack.Outputs.PublicSubnet3ID
        ProvisionBastionHost: "Disabled"
        ALBIngressController: "Disabled"
        EKSPublicAccessEndpoint: "Enabled"
      TemplateURL: !Sub 'https://v1-demo-environments.s3.amazonaws.com/utils/amazon-eks-entrypoint-existing-vpc.template.yaml'
    DependsOn: 
      - VPCStack
      - KeyPairStack

  KeyPairStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://v1-demo-environments.s3.amazonaws.com/utils/keypair.template.yaml'